let pizzaJson = [
  {
    id: 1,
    name: "Mussarela",
    img: "images/pizza.png",
    price: 20.19,
    sizes: ["100g", "530g", "860g"],
    description: "A tradição italiana com nossa deliciosa pizza de mussarela.",
  },
  {
    id: 2,
    name: "Margherita",
    img: "images/pizza2.png",
    price: 18.0,
    sizes: ["320g", "530g", "860g"],
    description:
      "A autêntica pizza Margherita - ingredientes frescos e sabor inigualável. Faça seu pedido agora!",
  },
  {
    id: 3,
    name: "Portuguesa",
    img: "images/pizza3.png",
    price: 17.45,
    sizes: ["320g", "530g", "860g"],
    description: "Descubra a autêntica pizza portuguesa em nosso cardápio!",
  },
  {
    id: 4,
    name: "Vegetariana",
    img: "images/pizza4.png",
    price: 19.77,
    sizes: ["320g", "530g", "860g"],
    description:
      "Experimente a nossa pizza vegetariana com ingredientes frescos e deliciosos!",
  },
  {
    id: 5,
    name: "Mineira",
    img: "images/pizza5.png",
    price: 21.43,
    sizes: ["320g", "530g", "860g"],
    description: "Descubra o sabor único da pizza mineira!",
  },
  {
    id: 6,
    name: "Moda da Casa",
    img: "images/pizza6.png",
    price: 18.55,
    sizes: ["320g", "530g", "860g"],
    description: "Experimente a pizza da casa: sabor único e irresistível!",
  },
  {
    id: 7,
    name: "Chocolate",
    img: "images/pizza7.png",
    price: 22.36,
    sizes: ["320g", "530g", "860g"],
    description: "Deliciosa pizza de chocolate para os amantes de sobremesa!",
  },
];
